rm_gimbal_bridge:
  ros__parameters:
    input_topic: "/dnn_node_sample"
    serial_port: "/dev/ttyS1"
    baud_rate: 921600
    image_width: 1280
    image_height: 1024
    image_center_x: 640.0
    image_center_y: 512.0
    min_confidence: 0.5
    enemy_prefix: ""
    selection_mode: "closest"
    log_selected_target: true
